version: "3.3"

services:
  app:
    network_mode: "host"
    image: sokol88/onvif-client:latest
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
