# This is a basic workflow to build and push a Docker image to Docker Hub.
name: Build and Push Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag container
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 --push -t ${{ secrets.DOCKERHUB_USERNAME }}/onvif-client:latest -f setup/app.Dockerfile .

      - name: Push container to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/onvif-client:latest
